// env.keys.ts
export const EnvKeys = {
  DATABASE_URL: 'DATABASE_URL',
  POSTGRES_PORT: 'POSTGRES_PORT',
  POSTGRES_USER: 'POSTGRES_USER',
  POSTGRES_PASSWORD: 'POSTGRES_PASSWORD',
  POSTGRES_DB: 'POSTGRES_DB',
  NODE_ENV: 'NODE_ENV',
  API_FORMAT: 'API_FORMAT',
  API_EXHIBITION_BASE_URL: 'API_EXHIBITION_BASE_URL',
  API_EXHIBITION_KEY: 'API_EXHIBITION_KEY',
  ADMIN_EMAIL: 'ADMIN_EMAIL',
  ADMIN_PASSWORD: 'ADMIN_PASSWORD',
  JWT_SECRET: 'JWT_SECRET',
  JWT_EXPIRES_IN: 'JWT_EXPIRES_IN',
  COOKIE_NAME: 'COOKIE_NAME',
  ADMIN_NICKNAME: 'ADMIN_NICKNAME',
} as const;
