// env.keys.ts
export const EnvKeys = {
  DATABASE_URL: 'DATABASE_URL',
  POSTGRES_PORT: 'POSTGRES_PORT',
  POSTGRES_USER: 'POSTGRES_USER',
  POSTGRES_PASSWORD: 'POSTGRES_PASSWORD',
  POSTGRES_DB: 'POSTGRES_DB',
  NODE_ENV: 'NODE_ENV',
  API_FORMAT: 'API_FORMAT',
  API_EXHIBITION_BASE_URL: 'API_EXHIBITION_BASE_URL',
  API_EXHIBITION_KEY: 'API_EXHIBITION_KEY',
} as const;
